# -*- coding: utf-8 -*-
"""CO2 EMISSION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ1W4oI-rW5hEamVmug7Xz7-0ESyT20I
"""

import pandas as pd
co2= pd.read_csv('/content/CO2 Emissions.csv')
co2

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

co2.shape

co2.head()

co2.info()

co2.isnull().sum()

co2.describe()

plt.figure(figsize=(8,5))
sns.histplot(co2['CO2 Emissions(g/km)'], bins=30, kde=True)
plt.title('Distribution of CO2 Emissions')
plt.show()

num_cols = ['Engine Size(L)', 'Fuel Consumption Comb (L/100 km)']
for col in num_cols:
    plt.figure(figsize=(8,4))
    sns.histplot(co2[col], bins=30, kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

cat_cols = ['Cylinders', 'Fuel Type', 'Transmission']
for col in cat_cols:
    plt.figure(figsize=(8,4))
    co2[col].value_counts().plot(kind='bar')
    plt.title(f'Count of {col}')
    plt.show()

num_co2 = co2[['Engine Size(L)', 'Fuel Consumption Comb (L/100 km)', 'CO2 Emissions(g/km)']]
plt.figure(figsize=(8,6))
sns.heatmap(num_co2.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

for col in cat_cols:
    plt.figure(figsize=(10,5))
    sns.boxplot(x=col, y='CO2 Emissions(g/km)', data=co2)
    plt.xticks(rotation=45)
    plt.title(f'CO2 Emissions by {col}')
    plt.show()

sns.pairplot(co2[['Engine Size(L)', 'Fuel Consumption Comb (L/100 km)', 'CO2 Emissions(g/km)']])
plt.show()